name: Build Container

on:
  release:
    types:
      - published

concurrency:
  group: ${{ github.workflow }}-deployer-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build-and-release:
    name: "Build"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Check out Code
        uses: actions/checkout@v3

      - name: Read .nvmrc
        id: node_version
        run: echo "$(cat .nvmrc)" && echo "NVMRC=$(cat .nvmrc)" >> $GITHUB_ENV
      - name: Enable Corepack
        run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NVMRC }}
          cache: "yarn"
          cache-dependency-path: yarn.lock

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build Storybook
        run: |
          yarn install --immutable
          yarn build
          yarn build-storybook 
          docker buildx build --platform linux/amd64 --push -t registry.min.dev/minio/mds .
          echo "${{ secrets.MDS_DEPLOYER_KUBECONFIG }}" > /tmp/kubecconfig
          ls -l /tmp/kubecconfig
          kubectl --kubeconfig /tmp/kubecconfig -n mds delete pod $(kubectl --kubeconfig /tmp/kubecconfig -n mds get pods | grep mds | awk '{print $1}')
